apiVersion: apps/v1
kind: Deployment
metadata:
  name: payflow-api
  namespace: payflow
  labels:
    app.kubernetes.io/name: payflow-api
    app.kubernetes.io/component: api
spec:
  revisionHistoryLimit: 5
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: payflow-api
  template:
    metadata:
      labels:
        app: payflow-api
        app.kubernetes.io/name: payflow-api
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: api
          image: ghcr.io/sayomiyori/payflow:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8088
          envFrom:
            - configMapRef:
                name: payflow-config
            - secretRef:
                name: payflow-secret
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
