apiVersion: v1
kind: Service
metadata:
  name: payflow-api
  namespace: payflow
  labels:
    app.kubernetes.io/name: payflow-api
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app: payflow-api
  ports:
    - name: http
      port: 80
      targetPort: 8088
      protocol: TCP
