apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: payflow-api
  namespace: payflow
  labels:
    app.kubernetes.io/name: payflow-api
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.payflow.example.com
      secretName: payflow-api-tls
  rules:
    - host: api.payflow.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: payflow-api
                port:
                  number: 80
