apiVersion: apps/v1
kind: Deployment
metadata:
  name: payflow-celery-beat
  namespace: payflow
  labels:
    app.kubernetes.io/name: payflow-celery-beat
    app.kubernetes.io/component: scheduler
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: payflow-celery-beat
  template:
    metadata:
      labels:
        app: payflow-celery-beat
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: celery-beat
          image: ghcr.io/sayomiyori/payflow:latest
          imagePullPolicy: Always
          command:
            - celery
            - -A
            - app.workers.celery_app.celery_app
            - beat
            - --loglevel=INFO
          envFrom:
            - configMapRef:
                name: payflow-config
            - secretRef:
                name: payflow-secret
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
