apiVersion: v1
kind: ConfigMap
metadata:
  name: payflow-config
  namespace: payflow
data:
  ENVIRONMENT: "production"
  ACCESS_TOKEN_EXPIRE_MINUTES: "15"
  REFRESH_TOKEN_EXPIRE_DAYS: "30"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  CLICKHOUSE_HOST: "clickhouse"
  CLICKHOUSE_PORT: "9000"
  CLICKHOUSE_DB: "payflow_analytics"
  YUKASSA_SHOP_ID: "replace-with-shop-id"
