"""initial

Revision ID: 3a780e8c4434
Revises:
Create Date: 2026-04-05 01:17:22.026035

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "3a780e8c4434"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
