"""

Revision ID: e0d0738a7d36
Revises: 3a780e8c4434
Create Date: 2026-04-05 15:09:47.233440

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "e0d0738a7d36"
down_revision: str | None = "3a780e8c4434"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
